remote_theme: chrisrhymes/bulma-clean-theme

repository: johannesegger/VuforiaStudioExtensions

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- jekyll-readme-index
- jekyll-remote-theme
- jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
      hero_height: is-small
  -
    scope:
      path: "challenges"
      type: pages
    values:
      menubar: challenges
